mm/urls.py
#coding=UTF-8
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^manage/',include('manage.urls')),
    (r'^doc/',include('doc.urls')),
    (r'^images/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.IMAGE_DIR}),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.CSS_DIR}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.JS_DIR}),
    (r'^docs/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.DOC_DIR}),
    

    (r'^$', 'business.views.index'),
    (r'^register/$', 'business.views.register'),
    (r'^register_ok/$', 'business.views.register_ok'),
    (r'^win_login/$', 'business.views.win_login'),
    (r'^login/$', 'business.views.login'),
    (r'^auth/$', 'business.views.auth'),

    (r'^alipay/return/$','business.views.alipay_return_url'),
    (r'^alipay/notify/$','business.views.alipay_notify_url'),

    
    (r'^public/main/$','business.views.main'),
    (r'^public/report/$','business.views.report'),
    (r'^public/report/day/((?:(?!0000)[0-9]{4}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[0-9]{2}(?:0[48]|[2468][048]|[13579][26])|(?:0[48]|[2468][048]|[13579][26])00)-02-29))$','business.views.report_day'),
    (r'^public/report/month/(\d{4}-(?:0[1-9]|1[0-2]))$','business.views.report_month'),
    (r'^public/report/year/(\d{4})$','business.views.report_year'),
    (r'^public/passwd/$','business.views.password'),
    (r'^public/help/$','business.views.help'),
    (r'^public/version/$','business.views.version'),
    (r'^public/buy/$','business.views.buy'),
    (r'^public/confirm/(\d{8}-\d{6}-\d{6})$','business.views.confirm'),
    (r'^public/pay/$','business.views.pay'),
    (r'^public/verify/(\d{8}-\d{6}-\d{6})$','business.views.verify'),

    
    (r'^setting/company/$','business.views.company_view'),
    
    (r'^setting/branch/$','business.views.branch'),
    (r'^setting/branch/new/$', 'business.views.branch_new'),
    (r'^setting/branch/edit/(\w{32})$', 'business.views.branch_edit'),
    (r'^setting/branch/delete/$', 'business.views.branch_delete'),
    (r'^setting/branch/select/$', 'business.views.branch_select'),
    
    (r'^setting/user/$', 'business.views.user'),
    (r'^setting/user/new/$', 'business.views.user_new'),
    (r'^setting/user/delete/$', 'business.views.user_delete'),
    (r'^setting/user/edit/(\w{32})$', 'business.views.user_edit'),

    (r'^setting/product/$', 'business.views.product'),
    (r'^setting/product/new/$', 'business.views.product_new'),
    (r'^setting/product/delete/$', 'business.views.product_delete'),
    (r'^setting/product/edit/(\w{32})$', 'business.views.product_edit'),

    (r'^setting/setup/$', 'business.views.setup'),

    (r'^business/unit/$', 'business.views.unit'),
    (r'^business/unit/new/$', 'business.views.unit_new'),
    (r'^business/unit/delete/$', 'business.views.unit_delete'),
    (r'^business/unit/edit/(\w{32})$', 'business.views.unit_edit'),
    (r'^business/unit/view/(\w{32})$', 'business.views.unit_view'),
   
    (r'^bill/recharge/$', 'business.views.bill_recharge'),

    (r'^bill/recharge/view/(\w{32})$', 'business.views.bill_recharge_view'),

    (r'^bill/recharge/value/$', 'business.views.bill_recharge_value'),
    (r'^bill/recharge/value/new/$', 'business.views.bill_recharge_value_new'),
    (r'^bill/recharge/value/edit/(\w{32})$', 'business.views.bill_recharge_value_edit'),
    
    (r'^bill/recharge/times/$', 'business.views.bill_recharge_times'),
    (r'^bill/recharge/times/new/$', 'business.views.bill_recharge_times_new'),
    (r'^bill/recharge/times/edit/(\w{32})$', 'business.views.bill_recharge_times_edit'),
    
    (r'^bill/sale/$', 'business.views.bill_sale'),
    (r'^bill/sale/value/view/(\w{32})$', 'business.views.bill_sale_value_view'),

    (r'^bill/sale/value/$', 'business.views.bill_sale_value'),
    (r'^bill/sale/value/new/$', 'business.views.bill_sale_value_new'),
    (r'^bill/sale/value/edit/(\w{32})$', 'business.views.bill_sale_value_edit'),
    
    (r'^bill/sale/times/$', 'business.views.bill_sale_times'),
    (r'^bill/sale/times/new/$', 'business.views.bill_sale_times_new'),
    (r'^bill/sale/times/edit/(\w{32})$', 'business.views.bill_sale_times_edit'),
            
    (r'^bill/delete/$','business.views.bill_delete'),
    (r'^bill/exe/$','business.views.bill_exe'),

    (r'^unit/select/$', 'business.views.unit_select'),
    (r'^unit/new/$', 'business.views.new_unit'),

    (r'^card/select/$', 'business.views.card_select'),
    
    (r'^card/value/select/$', 'business.views.card_value_select'),
    (r'^card/times/select/$', 'business.views.card_times_select'),      
    
    (r'^card/value/view/(\w{32})$', 'business.views.card_value_view'),
    (r'^card/times/view/(\w{32})$', 'business.views.card_times_view'),   
    
    (r'^product/select/$', 'business.views.select_product'),
    (r'^product/new/$', 'business.views.new_product'),



    
    (r'^err/no_access/$', 'business.views.err',{'err_id':1}),
    (r'^err/no_object/$', 'business.views.err',{'err_id':2}),
    (r'^err/no_program/$', 'business.views.err',{'err_id':3}),
    (r'^err/no_right/$', 'business.views.err',{'err_id':4}),
    (r'^err/no_enough_information/$', 'business.views.err',{'err_id':5}),
    (r'^err/record_already_exists/$', 'business.views.err',{'err_id':6}),
    (r'^err/oldpasswd_no_match/$', 'business.views.err',{'err_id':7}),
    (r'^err/newpasswd_no_match/$', 'business.views.err',{'err_id':8}),
    (r'^err/mobile_existed/$', 'business.views.err',{'err_id':9}),
    (r'^err/internal_error/$', 'business.views.err',{'err_id':10}),
    (r'^err/expired/$', 'business.views.err',{'err_id':11}),
    
    (r'^msg/passwd_change_ok/$', 'business.views.msg',{'msg_id':1}),
    
    (r'^dlg/no_more_branch/$', 'business.views.dlg',{'dlg_id':1}),
    (r'^dlg/no_more_unit/$', 'business.views.dlg',{'dlg_id':2}),

)

business/forms.py
#coding=UTF-8
from django import forms
from django.forms import ModelForm,TextInput
from models import *


class RegisterForm(forms.Form):
    company_name=forms.CharField(label='公司名称',widget=forms.TextInput(attrs={'class':'txt','size':'35'}))
    mobile=forms.CharField(label='手机',widget=forms.TextInput(attrs={'class':'txt','size':'35'}))
    password=forms.CharField(label='密码',widget=forms.PasswordInput(attrs={'class':'txt','size':'35'}))

class LoginForm(forms.Form):
    mobile=forms.CharField(label='手机',widget=forms.TextInput(attrs={'class':'login-textbox','placeholder':'手机'}))
    password=forms.CharField(label='密码',widget=forms.PasswordInput(attrs={'class':'login-textbox','placeholder':'密码','onkeydown':'onkey()'}))
    
class SearchForm(forms.Form):
    key_words=forms.CharField(widget=forms.TextInput(attrs={'class':'txt_search','autocomplete':'off'}))

class UnitForm(forms.Form):
    unit_name=forms.CharField(label='客户名称',widget=forms.TextInput(attrs={'class':'txt'}))
    mobile=forms.CharField(label='手机',required=False,widget=forms.TextInput(attrs={'class':'txt'}))

class CardForm(forms.Form):
    card_type=forms.CharField(label='卡类型',widget=forms.TextInput())
    cardno=forms.CharField(label='卡号',widget=forms.TextInput(attrs={'class':'txt'}))

class ProductForm(forms.Form):
    product_name=forms.CharField(label='商品名称',widget=forms.TextInput(attrs={'class':'txt'}))

class BranchForm(forms.Form):
    branch_name=forms.CharField(label='分店名称',widget=forms.TextInput(attrs={'class':'txt'}))
    
class UserForm(forms.Form):
    real_name= forms.CharField(label='职员姓名',widget=forms.TextInput(attrs={'class':'txt'}))
    branch_id=forms.CharField(label='分店id',widget=forms.TextInput(attrs={'class':'txt'}))
    branch_name=forms.CharField(label='分店',widget=forms.TextInput(attrs={'class':'txt'}))
    mobile = forms.CharField(label='手机',widget=forms.TextInput(attrs={'class':'txt'}))
    password = forms.CharField(label='密码',required=False,widget=forms.PasswordInput(attrs={'class':'txt'}))
    roles = forms.ModelMultipleChoiceField(label='角色',widget=forms.CheckboxSelectMultiple(),queryset=Role.objects.all())  

class SettingForm(forms.Form):
    CHOICES=[('1','充值卡'),
             ('2','计次卡'),
             ('3','混合模式')]
    card_type = forms.ChoiceField(label='卡类型',choices=CHOICES, widget=forms.RadioSelect())
    custom_price=forms.BooleanField(label='开启分店自定义商品价格',required=False)


class BillForm(forms.Form):
    card_id=forms.CharField(label='id',widget=forms.TextInput(attrs={'class':'txt'}))
    cardno=forms.CharField(label='卡号',widget=forms.TextInput(attrs={'class':'txt'}))

class RechargeValueForm(BillForm):
    money=forms.CharField(label='收款',widget=forms.TextInput(attrs={'class':'txt'}))
    amount=forms.DecimalField(label='充值',widget=forms.TextInput(attrs={'class':'txt'}))

class RechargeTimesForm(BillForm):
    money=forms.CharField(label='收款',widget=forms.TextInput(attrs={'class':'txt'}))
    times=forms.IntegerField(label='次数',widget=forms.TextInput(attrs={'class':'txt'}))

class SaleValueForm(BillForm):
    pass

class SaleTimesForm(BillForm):
    times=forms.IntegerField(label='次数',widget=forms.TextInput(attrs={'class':'txt'}))

    
class PasswordForm(forms.Form):
    oldpassword=forms.CharField(label='旧口令',widget=forms.PasswordInput(attrs={'class':'txt'}))
    password1 = forms.CharField(label='新口令',widget=forms.PasswordInput(attrs={'class':'txt'}))
    password2 = forms.CharField(label='确认新口令',widget=forms.PasswordInput(attrs={'class':'txt'}))

templates/base_dialog.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" /><!– IE8 mode –>
        <link rel="stylesheet" type="text/css" href="/css/page.css" />
        <link rel="stylesheet" type="text/css" href="/css/flick/jquery-ui-1.10.3.custom.css" />
        <script type="text/javascript" src="/js/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/js/jquery-1.9.1.post-csrf-patch.js"></script>
		<script type="text/javascript" src="/js/jquery-ui-1.8.19.custom.min.js"></script>
        <script type="text/javascript" src="/js/layer/layer.js"></script>
        <script type="text/javascript" src="/js/cserp.js"></script>
	{% block head %}{% endblock %}
    </head>
    <body>
	{% block content %}{% endblock %}
    </body>
</html>

templates/base_panel.html
{% extends "./base.html" %}
{% block content %}
	<div class="screen-width" style="min-height:400px;">
		<div class="main-panel" style="min-height:400px;">
		{% block panel %}
		{% endblock %}
		</div>
	</div>
{% endblock %}

templates/bill_recharge_times_new.html
{% extends "./base_panel.html" %}
{% block title %}
	<title>新增充值单</title>
{% endblock %}

{% block head %}
<script>
	$(function() {
		var fv = new formValidate('#frm'); 
		fv.init({});

		//绑定选择单位按钮
		bindButton('#ulist','#btnSelectCard','#id_card_id','#id_cardno','选择卡','/card/times/select/',2);
		
	});
</script>
{% endblock %}

{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		<a href="/public/main/">主页</a> -> <a href="/bill/recharge/times/">充值单</a> -> 新增充值单
	</div>


	<div class="content bg-white">
	<form id="frm" method="post" action="/bill/recharge/times/new/">
		{% csrf_token %}
		<div style="height:40px;">
			<input class="little-button button-red" type="submit" name="save" value="保存" />
			<a class="little-button button-blue"  onclick="javascript:history.go(-1);" href="javascript:void(0);">取消</a>
		</div>
		<ul id="ulist">
			<li class="form-li">{{f.card_id.as_hidden}}</li>
			<li class="form-li"><label>{{f.cardno.label}} </label>{{f.cardno}}<span></span>
			<span id="btnSelectCard" class="tiny-button button-green">选择</span>
			</li>
			<li class="form-li"><label>{{f.money.label}} </label>{{f.money}}<span></span> 元</li>
			<li class="form-li"><label>{{f.times.label}} </label>{{f.times}}<span></span> 次</li>
		</ul>
	</form>
	</div>
{% endblock %}

templates/bill_sale.html
{% extends "./base_panel.html" %}
{% load business_tags %}
{% block title %}
	<title>选择消费卡模式</title>
{% endblock %}

{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		<a href="/public/main/">主页</a> -> <a href="/bill/sale/">选择消费卡模式</a>
	</div>
	<div class="content bg-white">
		<div style="height:40px;">
		</div>
		<ul id="ulist">
			<a class="little-button button-blue" href="/bill/sale/value/new/">充值卡消费</a>
			<a class="little-button button-blue" href="/bill/sale/times/new/">计次卡消费</a>
		</ul>

	</div>
{% endblock %}

templates/bill_sale_times_edit.html
{% extends "./base_panel.html" %}
{% block title %}
	<title>修改消费单</title>
{% endblock %}

{% block head %}
<script>
 
	$(function() {
		var fv = new formValidate('#frm'); 
		fv.init({});
	
		//绑定选择单位按钮
		bindButton('#ulist','#btnSelectCard','#id_card_id','#id_cardno','选择卡','/card/times/select/',2);
		
	});
</script>
{% endblock %}

{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		<a href="/public/main/">主页</a> -> <a href="/bill/sale/times/">消费单</a> -> 修改消费单
	</div>


	<div class="content bg-white">
	<form id="frm"  method="post" action="/bill/sale/times/edit/{{b.id}}">
		{% csrf_token %}
		<div style="height:40px;">
			<input class="little-button button-red" type="submit" name="save" value="保存" />
			<a class="little-button button-blue" href="/bill/sale/times/">取消</a>
		</div>
		<ul id="ulist">
			<li class="form-li">{{f.card_id.as_hidden}}</li>
			<li class="form-li"><label>{{f.cardno.label}}</label> {{f.cardno}}<span></span>
			<span id="btnSelectCard" class="tiny-button button-green">选择</span>
			</li>
			<li class="form-li"><label>{{f.times.label}} </label>{{f.times}}<span></span> 次</li>
		</ul>

	</form>
	</div>
{% endblock %}

templates/business_report_day.html
{% extends "./base_panel.html" %}
{% load business_tags %}
{% block title %}
	<title>报表</title>
{% endblock %}
{% block head %}
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/flot/canvas.min.js"></script><![endif]-->
    <style type="text/css">
        #flot-placeholder{float:left;width:950px;height:200px;}        
    </style>
	<script type="text/javascript" src="/js/flot/jquery.flot.min.js"></script>
	<script type="text/javascript">
	    $(document).ready(function () {
		    var data1 = [{% for item in list1 %}[{{item.0}},{{item.1|floatformat:"2"}}],{% endfor %}];
		    //var data2 = [{% for item in list2 %}[{{item.0}},{{item.1|negative|floatformat:"2"}}],{% endfor %}];
		    var dataset = [
		    {label: "&nbsp;收入",data: data1},
		    //{label: "&nbsp;销售",data: data2}
		    ];
		    var options = {
		        series:{
		            lines:{ show: true },
		            points:{radius: 5,show: true},
					
		        },
		        grid:{
		        	hoverable:true,
		   
		        },
		        xaxis: {
		            ticks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,[24,'24/时']],
		            tickDecimals:0,
		        }
		    };
		    
	        $.plot($("#flot-placeholder"), dataset, options);
	        
		    function showTooltip(x, y, contents) {
		        $('<div id="tooltip">' + contents + '</div>').css( {
		            position: 'absolute',
		            display: 'none',
		            top: y + 5,
		            left: x + 5,
		            border: '1px solid #fdd',
		            padding: '2px',
		            'background-color': '#fee',
		            opacity: 0.80
		        }).appendTo("body").fadeIn(200);
		    }

		    var previousPoint = null;
		    $("#flot-placeholder").bind("plothover", function (event, pos, item) {
	            if (item) {
	                if (previousPoint != item.dataIndex) {
	                    previousPoint = item.dataIndex;
	                    
	                    $("#tooltip").remove();
	                    //x,y分别是该点x,y的值，可以用于showTooltip
	                    //(x-1)+点+item.series.label+y+"元"
	                    var x = item.datapoint[0],
	                        y = item.datapoint[1].toFixed(2);
	                    
	                    showTooltip(item.pageX, item.pageY,item.series.label+y+"元");
	                }
	            }
	            else {
	                $("#tooltip").remove();
	                previousPoint = null;            
	            }
		    });
	    });

	</script>
{% endblock %}

{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		<a href="/public/main/">主页</a> -> 报表
	</div>
	<div class="content bg-white">
		<div style="height:40px;">
		{% ifequal flag 1 %}
			<a id="btnYesterday" class="tiny-button" href="/public/report/day/{{td|addday:-1}}">昨天</a>
			<span id="btnToday" class="tiny-button button-red">今天</span>
		{% else %}
			<span id="btnYesterday" class="tiny-button  button-red" >昨天</span>
			<a id="btnToday" class="tiny-button" href="/public/report/day/{{td|addday:0}}">今天</a>
		{% endifequal %}
			<a id="btnMonth" class="little-button" href="/public/report/month/{{td|month}}">本月</a>
			<a id="btnYear" class="little-button" href="/public/report/year/{{td|year}}">本年</a>	
		</div>
	    <div style="background:#fff;height:100px;">
		    <ul style="margin:20px 20px 20px 20px;">
			    <li style="height:40px;">今日客户充值：<span  class="sv-font-xxl">{{ia}}</span>元</li>
		    </ul>
	    </div>
		<div id="flot-placeholder"></div>
	</div>
{% endblock %}

templates/business_report_year.html
{% extends "./base_panel.html" %}
{% load business_tags %}
{% block title %}
	<title>报表</title>
{% endblock %}
{% block head %}
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/flot/canvas.min.js"></script><![endif]-->
    <style type="text/css">
        #flot-placeholder{float:left;width:950px;height:200px;}        
    </style>
	<script type="text/javascript" src="/js/flot/jquery.flot.min.js"></script>
	<script type="text/javascript">
	    $(document).ready(function () {
		    var data1 = [{% for item in list1 %}[{{item.0}},{{item.1|floatformat:"2"}}],{% endfor %}];
		    //var data2 = [{% for item in list2 %}[{{item.0}},{{item.1|negative|floatformat:"2"}}],{% endfor %}];
		    var dataset = [
		    {label: "&nbsp;收入",data: data1},
		    //{label: "&nbsp;销售",data: data2}
		    ];
		    var options = {
		        series:{
		            lines:{ show: true },
		            points:{radius: 5,show: true},
					
		        },
		        grid:{
		        	hoverable:true,
		   
		        },
		        xaxis: {
		            ticks: [0,1,2,3,4,5,6,7,8,9,10,11,[12,'12/月']],
		            tickDecimals:0,
		        }
		    };
		    
	        $.plot($("#flot-placeholder"), dataset, options);
	        
		    function showTooltip(x, y, contents) {
		        $('<div id="tooltip">' + contents + '</div>').css( {
		            position: 'absolute',
		            display: 'none',
		            top: y + 5,
		            left: x + 5,
		            border: '1px solid #fdd',
		            padding: '2px',
		            'background-color': '#fee',
		            opacity: 0.80
		        }).appendTo("body").fadeIn(200);
		    }

		    var previousPoint = null;
		    $("#flot-placeholder").bind("plothover", function (event, pos, item) {
	            if (item) {
	                if (previousPoint != item.dataIndex) {
	                    previousPoint = item.dataIndex;
	                    
	                    $("#tooltip").remove();
	                    //x,y分别是该点x,y的值，可以用于showTooltip
	                    //(x-1)+点+item.series.label+y+"元"
	                    var x = item.datapoint[0],
	                        y = item.datapoint[1].toFixed(2);
	                    
	                    showTooltip(item.pageX, item.pageY,item.series.label+y+"元");
	                }
	            }
	            else {
	                $("#tooltip").remove();
	                previousPoint = null;            
	            }
		    });
	    });
	</script>
{% endblock %}

{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		<a href="/public/main/">主页</a> -> 报表
	</div>
	<div class="content bg-white">
		<div style="height:40px;">

			<a id="btnYesterday" class="tiny-button" href="/public/report/day/{{td|addday:-1}}">昨天</a>
			<a id="btnToday" class="tiny-button" href="/public/report/day/{{td|addday:0}}">今天</a>
			<a id="btnMonth" class="little-button" href="/public/report/month/{{td|month}}">本月</a>
			<span id="btnYear" class="little-button button-red">本年</span>	
		</div>
	    <div style="background:#fff;height:100px;">
		    <ul style="margin:20px 20px 20px 20px;">
			    <li style="height:40px;">本年客户充值：<span  class="sv-font-xxl">{{ia}}</span>元</li>
		    </ul>
	    </div>
		<div id="flot-placeholder"></div>
	</div>
{% endblock %}

templates/public_buy.html
{% extends "./base_panel.html" %}
{% block title %}
	<title>购买</title>
{% endblock %}
{% block head %}
<script type="text/javascript">
	$(document).ready(function(){
		$('.pan').click(function() {
				$('.pan').removeClass('on');
				$('#product-id').attr('value', $(this).attr('id'));
				$(this).addClass('on');
		    });
		$('#pay').click(function() {
	        if ($('#product').find('span').hasClass('on')) {
				$.layer({
					type: 1,   //0-4的选择,
				    title: "选择支付方式",
				    border: [0],
				    closeBtn: [1,true],
				    shadeClose: true,
				    area: ['700px', '400px'],
					offset : ['100px', '250px'],
				    page: {dom : '.bank'}
				});
	        };
		});
	    $('.bank .bank-list a').hover(function() {
	        $(this).addClass('on');
	    }, function() {
	        $(this).removeClass('on');
	    });
	    $('.bank .bank-list a').click(function() {
	        $('.bank .bank-list a').removeClass('on');
	        $(this).addClass('on');
	        $('#ruready #bank-id').attr('value', $(this).find('img').attr('bankid'));
	        $('#imready').click();
	
	    });
		$('#imready').submit(function() {
	        if ( $('#bank-id').val() == '' || $('#product-id').val() == '' ) {
	            return false;
	        };
		});
	});
</script>
{% endblock %}
{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		{% if u %}
		<a href="/public/main/">
		{% else %}
		<a href="/">
		{% endif %}
		主页</a> -> 购买
	</div>

	<div class="content bg-white">
		<div>
		    <form id="ruready" action="/public/buy/" method="post">
		    	{% csrf_token %}
		    	<input type='hidden' name='product_id' id='product-id'>
	            <input type='hidden' name='bank_id' id='bank-id'>
	            <input type="submit" style="display:none;" id="imready">
            </form> 
		</div>
		<div id="product" class="align-center h200">
			<span class="pan" id="1001"><p>&nbsp;</p><p class="red">月卡：￥85元/月</p><p>&nbsp;</p></span>
			<span class="pan" id="1002"><p class="red">季卡：￥210元/季</p><p class="cancel">￥255元/季</p><p>优惠￥45元</p></span>
			<span class="pan" id="1003"><p class="red">年卡：￥600元/年</p><p class="cancel">￥960元/年</p><p>优惠￥360元</p></span>
		</div>
		<div class="align-center h80">
			<span id="pay" class="button button-red align-center mgt30">立即支付</span>
		</div>
		<br/><br/><br/><br/><br/>
	</div>
	<div class="bank" style="display:none;">
	    <div class="bank-list">
	    {% for item in list %}
			{% ifchanged item.type %}
				<br/>
			{% endifchanged %}
	    	<a href="javascript:;"><span></span><img src="/images/bank_icons/{{item.img_url}}" alt="{{item.bank_name}}" bankid="{{item.gateway}}|{{item.id}}" ></a>
	    {% endfor %}
		</div>
	</div>
{% endblock %}

templates/public_password.html
{% extends "./base_panel.html" %}
{% block title %}
	<title>修改口令</title>
{% endblock %}

{% block head %}
<script>
	$(function() {
		var fv = new formValidate('#frm'); 
		fv.init({}); 
	});
</script>
{% endblock %}

{% block panel %}
	<div class="content bg-ll-blue" style="height:35px;line-height:35px;">
		<a href="/public/main/">主页</a> -> 修改口令
	</div>


	<div class="content bg-white">
	<form id="frm"  method="post" action="/public/passwd/">
		{% csrf_token %}
		<div style="height:40px;">
			<input class="little-button button-red" type="submit" name="save" value="保存" />
			<a class="little-button button-blue" href="/public/main/">取消</a>
		</div>
			<ul id="ulist">
				<li class="form-li"><label>{{f.oldpassword.label}} </label>{{f.oldpassword}}<span></span></li>
				<li class="form-li"><label>{{f.password1.label}} </label>{{f.password1}}<span></span></li>
				<li class="form-li"><label>{{f.password2.label}} </label>{{f.password2}}<span></span></li>
			</ul>
	</form>
	</div>
{% endblock %}

templates/register_ok.html
{% extends "./base_panel.html" %}
{% block title %}
	<title>注册成功</title>
{% endblock %}
{% block head %}
<script>
	$(function() {
		//绑定登录按钮
		bindButtonJump('#divButton','#btnLogin','/main/','登录','/win_login/',1);
	});
</script>
{% endblock %}
{% block panel %}
<div>
	<div class="wait">
			<h2 class="success">注册成功！</h2>
	</div>
	<div align="center" valign="middle" >

		<div id="divButton">
			<a id="btnLogin" class="btn-footer" href="#">马上登录</a>
		</div>
	</div>
</div>

{% endblock %}